In [3]:
import numpy as np

A = np.array([[0.2161, 0.1441], [1.2969, 0.8648]])
b = np.array([0.1440, 0.8642])

x_t = np.array([0.9911, -0.4870])

r = b - A@x_t # matrix multiplication
r

array([-1.00000000e-08,  1.00000002e-08])

In [8]:
np.linalg.solve(A, b) # solution of a x = b for x

array([ 2., -2.])

array([0.144 , 0.8642])